### ISSUE TITLE
No toolbar menu after launching

### ISSUE THREAD

**Issue by SanaShporlyuk** [gyunaev/spivak#1]
Ubuntu 16

The menu bar and the toolbar are missing after launching.
STR:
1. Run app (src/spivak)
Actual result: opened window doesn't display main menu. User can not select song. Toolbar appears after changing window's size (maximize and minimize)
Expected result:
Toolbar menu should be displayed at window's top. 
![bug](https://cloud.githubusercontent.com/assets/23021102/25405482/4c6a6852-29b8-11e7-8844-f63c88dad352.png)

**Comment by gyunaev** [comment]
The player does not come with a toolbar.

**Comment by gyunaev** [comment]
That's how Ubuntu works, menu is hidden by the application.
