### ISSUE TITLE
Crash when playing song from empty Music queue

### ISSUE THREAD

**Issue by SanaShporlyuk** [gyunaev/spivak#10]
# Priority/Severity: Medium/Critical
Environment: Ubuntu 16.04, 64 bit
Karaoke version 1.3

The user has background music and used it (songs are loaded). If a user turns off music player or change directory to a path where no songs, player crashes during playing song. Looks like Karaoke doesn't refresh settings after saving changes. 

STR:
1. Run player=> File=>Preferences...=>Music tab
2. Check checkbox "Enable the music player.." at top
3. Add music file directory with music files => ok
4. Go to Control menu => Start playing
5. Stop song
6. File=>Preferences...=>Music tab
7. Uncheck "Enable the music player.." (or change music directory to path with no songs) => Ok 
8. Go to Control menu => Start playing

Actual result:
Crash occurs

Expected result:
Player works, no crash, Spivak Karaoke Player window is displayed

[log.txt](https://github.com/gyunaev/spivak/files/1675792/log.txt)

**Comment by gyunaev** [comment]
Thank you Sana, this one was a very tricky one for you to catch! Appreciated!
