### ISSUE TITLE
Can't change font of lyric.

### ISSUE THREAD

**Issue by thegioitrucquan** [gyunaev/spivak#13]
By defaut, program choice Piroto Light font which had not display vietnamese lyrics. But when i change another font, suprise, it's not save. Help me to changing font for display vietnamese lyrics, please! I'd already installed microsoft fonts (arial, time new roman, courier,...)

**Comment by gyunaev** [comment]
Fixed in b3886d0, thanks!

**Comment by franckgaga** [comment]
@gyunaev I'm running on the flathub version on linux (v1.4). Same bug as above, is it normal ?
