### ISSUE TITLE
How to access database?

### ISSUE THREAD

**Issue by thichhatho** [gyunaev/spivak#15]
Anyone help me!
+ Could you give me how to access database?
+ Why program couldn't export audio via Bluetooth speaker while via Analog it OK ? 
+ I couldn't queue song from database on program?

**Comment by gyunaev** [comment]
Hi, this part is for submitting issues in the application. Please use the [Spivak support forum](http://forum.ulduzsoft.com/forumdisplay.php?fid=10) for general support issues.
