### ISSUE TITLE
no cld2 packages on gentoo

### ISSUE THREAD

**Issue by sergeyglazyrindev** [gyunaev/spivak#17]
Hello, what could you suggest me to compile this project on gentoo ?
It's failing with such error:
languagedetector.cpp:23:42: fatal error: cld2/public/compact_lang_det.h: No such file or directory

**Comment by sergeyglazyrindev** [comment]
I've installed cld2.. but seems like there's no sources properly installed.... (do i need to copy sources to any place ?)

**Comment by gyunaev** [comment]
You need to install the development package of cld2, not just the binary library.

**Comment by sergeyglazyrindev** [comment]
yeah, I thought about it.... but on gentoo there's no cld dev package, okay I solved it.
