### ISSUE TITLE
failed to initialize the audio system

### ISSUE THREAD

**Issue by sergeyglazyrindev** [gyunaev/spivak#18]
Hello
I've got this message: "Failed to initialize the audio system: Audo plugin cannot be loaded" when compiled sources and executed binary
![Selection_012](https://user-images.githubusercontent.com/2778340/62517290-60df6800-b827-11e9-9e57-d27f78b8d481.png)

**Comment by gyunaev** [comment]
Please copy the libmediaplayer*.so* to where `ld` can find them.

**Comment by sergeyglazyrindev** [comment]
thank you so much
finally i compiled it
