### ISSUE TITLE
Crash when try to play removed song from karaoke queue window

### ISSUE THREAD

**Issue by SanaShporlyuk** [gyunaev/spivak#2]
Ubuntu 16.04 LTS
This bug appears randomly

STR:
1. open window Karaoke queue and add songs  
2. play song and stop it
3. remove the song
4. Click play button
See log
[log.txt](https://github.com/gyunaev/spivak/files/962143/log.txt)

**Comment by gyunaev** [comment]
Can't reproduce. Added a couple extra checks; please check again!
