### ISSUE TITLE
compile instruction for osx

### ISSUE THREAD

**Issue by magimat** [gyunaev/spivak#20]
Hi,

I'm desperatly looking for a CDG player which supports video background so I am really interested in your player, but could you give me some instructions on how to compile it for mac ?

**Comment by gyunaev** [comment]
https://github.com/gyunaev/spivak/releases includes Mac build. Otherwise see the Compiling section in readme.

**Comment by Symbian9** [comment]
@gyunaev any plans for next release?

**Comment by gyunaev** [comment]
In two weeks or so.
