### ISSUE TITLE
Add in queue more than one song

### ISSUE THREAD

**Issue by Kazun3500** [gyunaev/spivak#21]
Is it possible to add several files to the playback queue at once? For example, all files of one artist?

**Comment by gyunaev** [comment]
Yes, using either the management interface (in application UI).

**Comment by elmonitis** [comment]
> Is it possible to add several files to the playback queue at once? For example, all files of one artist?

I'm looking for this function, too.  Perhaps drag-and-drop functionality for several files at the same time.

**Comment by gyunaev** [comment]
Yes, using drag-and-drop.

**Comment by elmonitis** [comment]
> Yes, using drag-and-drop.

I'm using the AppImage version on Ubuntu 20.04.3.  Drag and drop doesn't seem to work when I multi-select files from a folder window into the Spivak Karaoke Player's main window or its Karaoke Queue window.  The Spivak version is 1.4 (released on January 7, 2019).  Any advice, please?

**Comment by gyunaev** [comment]
Please rebuild and check now, should be fixed.
