### ISSUE TITLE
Segfault on drag and drop in queue search

### ISSUE THREAD

**Issue by Kazun3500** [gyunaev/spivak#22]
1) Open karaoke queue window
2) Search something at right
![image](https://user-images.githubusercontent.com/13629272/68528467-1e389a80-0304-11ea-9e16-9295bd0fde28.png)
3) Drag item from list and drop it in queue
![image](https://user-images.githubusercontent.com/13629272/68528492-648df980-0304-11ea-8455-f041bf49f5f6.png)
4) Seqfault, no any other info in console

**Comment by gyunaev** [comment]
Should be fixed in current.
