### ISSUE TITLE
Poor performance with large collection on slow network media

### ISSUE THREAD

**Issue by jose1711** [gyunaev/spivak#24]
https://github.com/gyunaev/spivak/blob/11cf737c111d710e48645defa58db189123ac3eb/src/karaokeplayable_file.cpp#L48

Scanning all files inside a directory in order to find a matching mp3 to a cdg file is a bad idea when files are residing on slow nas. I wish there was an option to first try if basename + '.mp3' exists and if so, use it.
```
  QFileInfo musicinfo( m_baseFile );
  m_musicObject = musicinfo.baseName() + ".mp3";
```

**Comment by gyunaev** [comment]
Has to handle case sensitivity on Windows, i.e. ABBA.mp3 and abba.cdg must match. But I can add another check first.

**Comment by jose1711** [comment]
Another option would be to scan the filelist at startup and then cache it. As normally song list tends to be static.

**Comment by gyunaev** [comment]
> Another option would be to scan the filelist at startup and then cache it. As normally song list tends to be static.

This would only work if your whole collection is very small. Enumerating a large collection at startup is also a major hassle - my collection is about 70Gb total and will take a while.

**Comment by gyunaev** [comment]
> Scanning all files inside a directory in order to find a matching mp3 to a cdg file is a bad idea when files are residing on slow nas. I wish there was an option to first try if basename + '.mp3' exists and if so, use it.

This code is also used to find matching lyrics to music (i.e. passed MP3 and trying to match lyrics file), so it is much more complicated.
