### ISSUE TITLE
Issue with webserver redirect

### ISSUE THREAD

**Issue by andresava** [gyunaev/spivak#27]
Hi there!

Thanks again for you awesome project. I'm having some issues with the webserver, since I'm unable to connect.
Sorry if this may seem stupid... When I try to access to the server with the browser I get that login.html is not found, and spivak log says:

9;0]Unable to query physical screen size, defaulting to 100 dpi.
To override, set QT_QPA_EGLFS_PHYSICAL_WIDTH and QT_QPA_EGLFS_PHYSICAL_HEIGHT (in millimeters).
DEBUG WebServer: listening at port 8000
Found GStreamer libraries in PATH/LD_LIBRARY_PATH
xdg-screensaver: Window 3 does not exist
DEBUG WebServer: new HTTP connection
DEBUG WwwServer: GET /, logged: , body 
DEBUG WebServer: new HTTP connection
DEBUG WwwServer: GET /index.html, logged: , body 
DEBUG WebServer: new HTTP connection
DEBUG WwwServer: GET /login.html, logged: , body 
**DEBUG WebServer: requested path /login.html is not found in resources**
DEBUG WebServer: new HTTP connection
DEBUG WebServer: new HTTP connection

It seems to me that I did not configure the application properly...

Thank you!
A.

**Comment by gyunaev** [comment]
This is strange. Did you build it yourself?
