### ISSUE TITLE
Button 'Remove/Edit' work even song in not selected

### ISSUE THREAD

**Issue by SanaShporlyuk** [gyunaev/spivak#3]
Ubuntu 16

Looks like focus is on last song after opening Karaoke queue window. But selection does not display orange colour. In this case Button 'Remove' and 'Edit' works.
STR:
1. File=>Play file (add 2 songs)
2. Windows=>Karaoke queue
3. Click "Remove"
Actual result:
Last song is removed , but was not selected

**Comment by gyunaev** [comment]
Do the buttons work (i.e. perform something/crash when you click on them), or the issue is that they are being active?
