### ISSUE TITLE
Ultrastar video ignored

### ISSUE THREAD

**Issue by jose1711** [gyunaev/spivak#31]
This is probably a feature request as I don't believe Spivak is currently supposed to show a video reference in Ultrastar's `.txt` file.

**Comment by gyunaev** [comment]
No, it is not. Spivak is generally not designed to show video, audio AND lyrics at the same time. So it is parsed, but ignored.

**Comment by jose1711** [comment]
Oh, I see. That basically means that *if* a video is supposed to be loaded and played then it is supposed to contain lyrics. As this may come as a surprise for users knowing Ultrastar and the-likes maybe it deserves a note in README?

**Comment by gyunaev** [comment]
Good point. Updated README.

**Comment by gyunaev** [comment]
I mean, technically it could do this with code changes, but I see little value implementing it. Spivak was designed to be a Karaoke player only, there was no intent to make it an Ultrastar player keeping up-to-date with all new format features.
