### ISSUE TITLE
Audio plugin cannot be loaded (latest version from git)

### ISSUE THREAD

**Issue by jose1711** [gyunaev/spivak#32]
This is what I am getting after compiling the latest HEAD:

![obrázok](https://user-images.githubusercontent.com/1406222/97544674-3b112680-19ca-11eb-8d2f-c856fe5608eb.png)

```
$ spivak
DEBUG Background objects: 5 loaded
DEBUG Background objects: 5 loaded
Found GStreamer libraries in PATH/LD_LIBRARY_PATH
ERROR Failed to load media player library libmediaplayer_spivak via dlopen: Cannot load library libmediaplayer_spivak: (libmediaplayer_spivak: cannot open shared object file: No such file or directory)
Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 2417456450 (0x90177542)
 at -e line 16.
DEBUG KaraokeWidget::stop
DEBUG KaraokeWidget::stopped
```

Arch Linux x86_64, compiled from [AUR](https://aur.archlinux.org/packages/spivak-git/)

**Comment by gyunaev** [comment]
libmediaplayer_spivak.so (and all symlinks) must be somewhere it can be dlopen()ed from. Either copy them to /usr/lib or such, or do:
export LD_LIBRARY_PATH=/path/to/those/libs

**Comment by jose1711** [comment]
the only `.so` file that gets created during compilation is `plugin_langdetect.so` (after reenabling it)

**Comment by jose1711** [comment]
I ran bisect and found that commit d26faa655696edad276a35ca8195ff1882c1629e  broke the audio for my system.

**Comment by gyunaev** [comment]
Well its a huge change, but this is NOT the reason you can't load libmediaplayer_spivak.so

Have you done git clone, qmake and make? without using those scripts someone (who didn't understand what he was doing) created?

**Comment by jose1711** [comment]
Thank you, you were right. This has been a packaging issue. As I took over the maintenance of `spivak` in AUR and also created `spivak-git` I am wondering if there's a way to integrate it better with Autotools and instead of having to copy executable, icons and plugins separately also allow a standard way of relocating the data by means of `make DESTDIR=$pkgdir install` (as if frequently seen with other software). But maybe this should go into a separate issue.

Also, the problem is fixed in the updated [PKGBUILD](https://aur.archlinux.org/packages/spivak-git/) (and language plugin is reenabled).

**Comment by gyunaev** [comment]
You're welcome to add the install targets :)
