### ISSUE TITLE
Pitch option disabled (greyed out)

### ISSUE THREAD

**Issue by jose1711** [gyunaev/spivak#33]
Tested with CDG and MIDI.

![obrázok](https://user-images.githubusercontent.com/1406222/97968862-84dd8080-1dbf-11eb-93e7-3686efeb2ec5.png)

I suspect I need `plugin_pitchchanger` but I failed to find it in the sources.

**Comment by gyunaev** [comment]
This plugin is not yet up-to-date with the latest GStreamer, and thus is not part of the source.

**Comment by lucrus73** [comment]
Any chances to see the plugin updated? I know nothing about Gstreamer, but at least I'm a software developer... may I somehow help out with this?
