### ISSUE TITLE
Flatpak using an unsuported runtime

### ISSUE THREAD

**Issue by MarvinMep** [gyunaev/spivak#36]
Since I installed spivak from flathub I've got a message informing that org.kde.Platform is in the end of live when I do "flatpak update". I tried to remove manually org.kde.Platform but I couldn't because `org.kde.Platform/x86_64/5.11 is necessary for com.github.gyunaev.spivak/x86_64/stable`.

Here is the message 'flatpak update' shows: 
`org.kde.Platform está em fim de vida, com motivo: The KDE 5.11 runtime is no longer supported and does not receive security updates. We strongly recommend migrating to a supported runtime. Please ask your application developer to migrate to a supported runtime.`

**Comment by gyunaev** [comment]
Please check with Flatpak maintainers since I didn't build this one.
